package com.netflix.sunjeetsonboardingroot.startup;

import com.google.inject.Injector;
import com.netflix.governator.InjectorBuilder;
import com.netflix.governator.guice.servlet.WebApplicationInitializer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * The "main" class that boots up the service. For local testing one simply invokes the
 * main() method as if running a normal Java app.
 *
 * @author This file is auto-generated by runtime@netflix.com. Feel free to modify.
 */
public class SunjeetsOnboardingRoot implements WebApplicationInitializer {

    private static final Logger logger = LoggerFactory.getLogger(SunjeetsOnboardingRoot.class);

    public static void main(String[] args) throws Exception {
        logger.info("SNAP: Stepped in main");

        // publishEndlessly();

    }

    @Override
    public Injector createInjector() {
        logger.info("SNAP: created SunjeetsOnboardingRootModule injector");
        return InjectorBuilder.fromModules(new SunjeetsOnboardingRootModule()).createInjector();
    }
}
