package com.netflix.vms.transformer.config;

import com.netflix.archaius.api.annotations.Configuration;
import com.netflix.archaius.api.annotations.DefaultValue;

/**
 * This is the root config of the service. Simply inject it to constructors of any objects you
 * need to configure. To benefit from dynamic properties simply call the method to retrieve the
 * property value in your "hot path" code. No need to store it in a local or class variable.
 *
 * Check out the application.properties file to see how they can be set as properties.
 *
 * @author This file is auto-generated by runtime@netflix.com. Feel free to modify.
 */
@Configuration(prefix = "vms")
public interface VideometadataTransformerConfig {

    @DefaultValue("defaultConverterVip")
    String getConverterVip();


    @DefaultValue("defaultTransformerVip")
    String getTransformerVip();

}
