site_name: Hollow (Netflix OSS)
repo_url: 'https://github.com/Netflix/hollow'

nav:
  - Introduction: 'index.md'
  - Quick Start: 'quick-start.md'
  - Getting Started: 'getting-started.md'
  - Indexing/Querying: 'indexing-querying.md'
  - Infrastructure Hooks: 'infrastructure.md'
  - Producers and Consumers: 'producer-consumer-apis.md'
  - Tooling: 'tooling.md'
  - Data Modeling: 'data-modeling.md'
  - Diving Deeper: 'diving-deeper.md'
  - Interacting with a Hollow Dataset: 'interacting-with-a-dataset.md'
  - Data Ingestion: 'data-ingestion.md'
  - Validation: 'validation.md'
  - Advanced Topics: 'advanced-topics.md'
  - Testing: 'testing.md'
  - Glossary: 'glossary.md'
  - Community: 'community.md'
  - Acknowledgements: 'acknowledgements.md'
  - License: 'license.md'

theme:
  name: material
  logo: img/logo_white_bg.png
  font:
    text: Robot
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.share
    - search.highlight
    - search.suggest

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: brown
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: brown
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - css/extra.css

plugins:
  - search

# There are many available formatting extensions available, please read:
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - meta
  - toc:
      permalink: true
  - abbr
  - admonition
  - footnotes
  - tables
  # ----
  # Support annotations,
  # ref https://squidfunk.github.io/mkdocs-material/reference/annotations/
  - attr_list
  - md_in_html
  # -----
  # pymdownx
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - type: 'github'
      icon: fontawesome/brands/github-alt
      link: 'https://github.com/Netflix/hollow'
    - type: 'gitter'
      icon: fontawesome/brands/gitter
      link: 'https://gitter.im/Netflix/hollow'
