package com.netflix.sunjeetsonboardingroot.model;

import com.netflix.niws.IPayload;
import com.netflix.niws.PayloadConverter;

/**
 * This is an example of an object accessed through the RESTful service.
 *
 * To parse as JSON from Jersey you must implement the IPayload interface.
 * Also you need the Jackson payload converter so your JSON is parsed naturally
 * like {"userEmail":"email@netflix.com", "firstName":"Joe", "message":"Hello"}
 * Otherwise, the default converter by XStream requires passing the full class name
 * as part of the JSON object which leads to a bad data schema.
 *
 * @author This file is auto-generated by runtime@netflix.com. Feel free to modify.
 */
@PayloadConverter("com.netflix.niws.JacksonPayloadConverter")
public class Greeting implements IPayload {
    // Email is our primary key.
    private String userEmail;
    private String firstName;
    private String message;

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}
