package com.netflix.sunjeetsonboardingroot.model;

import java.util.Optional;

/**
 * Our model for storing and accessing greetings per user.
 *
 * @author This file is auto-generated by runtime@netflix.com. Feel free to modify.
 */
public interface SunjeetsOnboardingRootDao {

    Optional<Greeting> loadGreeting(String userEmail);

    void storeGreeting(Greeting greeting);
}
