package com.netflix.sunjeetsonboardingroot.model;

import com.google.common.collect.Maps;

import javax.inject.Inject;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * A dummy in-memory greeting store to use for local testing and debugging.
 *
 * @author This file is auto-generated by runtime@netflix.com. Feel free to modify.
 */
public class SunjeetsOnboardingRootInMemoryDao implements SunjeetsOnboardingRootDao {

    private Map<String, List<String>> table;

    @Inject
    public SunjeetsOnboardingRootInMemoryDao() {
        table = Maps.newConcurrentMap();
    }

    @Override
    public Optional<Greeting> loadGreeting(String userEmail) {
        return Optional
                .ofNullable(table.get(userEmail))
                .map((row) -> {
                    Greeting greeting = new Greeting();
                    greeting.setFirstName(row.get(0));
                    greeting.setUserEmail(row.get(1));
                    greeting.setMessage(row.get(2));
                    return greeting;
                });
    }

    @Override
    public void storeGreeting(Greeting greeting) {
        List<String> row = new ArrayList<>();
        row.add(greeting.getFirstName());
        row.add(greeting.getUserEmail());
        row.add(greeting.getMessage());
        table.put(greeting.getUserEmail(), Collections.unmodifiableList(row));
    }
}
