package com.netflix.vms.transformer.startup;

import static java.lang.String.join;

import com.google.common.collect.Maps;
import com.netflix.server.base.NFFilter;
import com.netflix.vms.transformer.health.TransformerHealthStatusServlet;
import com.sun.jersey.api.core.PackagesResourceConfig;
import com.sun.jersey.api.core.ResourceConfig;
import com.sun.jersey.guice.JerseyServletModule;
import com.sun.jersey.guice.spi.container.servlet.GuiceContainer;

import java.util.HashMap;
import java.util.Map;

/**
 * We use this module to wire up our endpoints.
 *
 * @author This file is auto-generated by runtime@netflix.com. Feel free to modify.
 */
public final class JerseyModule extends JerseyServletModule {
    @Override
    protected void configureServlets() {
        // We need those filter parameters to enable request tracing for our service for in/outbound
        // requests.
        // NFFilter then intercepts them and adds tracing information to request/response headers.
        Map<String, String> initParams = Maps.newHashMap();
        initParams.put("requestId.accept", "true");
        initParams.put("requestId.require", "true");
        //initParams.put(ResourceConfig.FEATURE_DISABLE_WADL, "true");
        //initParams.put(PackagesResourceConfig.PROPERTY_PACKAGES, join(";",
        //        "com.sun.jersey",
        //        "com.netflix.niws",
        //        "com.netflix.vms.transformer.rest"));
        filter("/*").through(NFFilter.class, initParams);

        // This sets up Jersey to serve any found resources that start with the base path of "/REST/"
        Map<String, String> containerParams = new HashMap<String, String>();
        containerParams.put(ResourceConfig.FEATURE_DISABLE_WADL, "true");
        containerParams.put(PackagesResourceConfig.PROPERTY_PACKAGES, join(";",
                "com.sun.jersey",
                "com.netflix.niws",
                "com.netflix.vms.transformer.rest"));
        serve("/REST/*").with(GuiceContainer.class, containerParams);

        // Set up the healthcheck endpoint to be set by the provided status servlet.
        serve("/healthcheck").with(TransformerHealthStatusServlet.class);
    }

    @Override
    public boolean equals(Object obj) {
        return obj != null && getClass().equals(obj.getClass());
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
