package com.netflix.vms.transformer.resource.v1;

import com.netflix.spectator.api.Counter;
import javax.inject.Singleton;
import javax.ws.rs.Path;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This is our "Controller" portion of our Model-View-Controller pattern.
 * It is responsible for handling requests for getting and setting greetings
 * for a Netflix user.
 * <br>
 * To GET a Greeting try:
 * <br>
 * <br>
 * curl localhost:8080/REST/v1/hello/dwight@netflix.com
 * <br>
 * <br>
 * To POST a Greeting try:
 * <br>
 * <br>
 * curl -X POST -H "Content-Type: application/json"
 * --data '{"userEmail":"dwight@netflix.com","firstName":"Dwight","message":"Hey"}'
 * localhost:8080/REST/v1/hello
 * <br>
 * <br>
 * This is not the only way you can expose REST interfaces.
 * For more examples on how to use Jersey to configure your REST API, please check out the
 * Jersey User Guice.
 *
 * @author This file is auto-generated by runtime@netflix.com. Feel free to modify.
 */
@Singleton
@Path("v1/hello")
public final class VideometadataTransformerResource {
    private static final Logger logger = LoggerFactory.getLogger(VideometadataTransformerResource.class);

    //private final Counter numTimesGreetingIsSetCounter;

    /** Where we keep our greetings for each user. */
    //private final VideometadataTransformerDao videometadataTransformerDao;

    /** Where we keep our configurations that we can dynamically access via the property getters. */
    /*private final VideometadataTransformerConfig config;

    @Inject
    public VideometadataTransformerResource(
            VideometadataTransformerDao videometadataTransformerDao,
            VideometadataTransformerConfig config,
            Registry registry) {
        this.videometadataTransformerDao = videometadataTransformerDao;
        this.config = config;
        this.numTimesGreetingIsSetCounter = registry.counter("VideometadataTransformerResource.numTimesGreetingIsSet");
    }

    @Path("{user}")
    @GET
    @Produces({MediaType.APPLICATION_JSON})
    public Greeting getGreeting(@PathParam("user") String userEmail) {
        logger.debug("Got a request for a greeting for {}", userEmail);

        Greeting greeting = videometadataTransformerDao.loadGreeting(userEmail).orElseGet( () -> {
            Greeting annonymousGreeting = new Greeting();
            annonymousGreeting.setUserEmail(userEmail);
            annonymousGreeting.setFirstName(config.getDefaultAnonymousName());
            annonymousGreeting.setMessage(config.getDefaultGreeting());
            return annonymousGreeting;
        });

        if (config.isLoudGreeting()) {
            greeting.setMessage(greeting.getMessage().toUpperCase());
        }
        return greeting;
    }

    @POST
    @Produces({MediaType.APPLICATION_JSON})
    @Consumes({MediaType.APPLICATION_JSON})
    public String setGreeting(Greeting greeting) {
        videometadataTransformerDao.storeGreeting(greeting);
        numTimesGreetingIsSetCounter.increment();
        return "\"OK\"";
    }*/
}
