package com.netflix.vms.transformer.namedlist;

public enum VideoNamedListType {

    VALID_VIDEOS,
    SENSITIVE_VIDEOS,
    VALID_SUPPLEMENTALS,
    ED_SUPPLEMENTALS,
    VALID_TOP_NODES,
    UNKNOWN_NODE_TYPE,
    VALID_3D_VIDEOS,
    VALID_ED_VIDEOS,
    VALID_ORIGINAL_TOP_NODES,
    VALID_ORIGINAL_VIDEOS,
    ED_VIDEOS,
    ED_TOP_NODES,
    ED_SHOWS,
    ED_SEASONS,
    ED_MOVIES,
    ED_EPISODES,
    ED_UNKNOWN_NODE_TYPE,
    ED_VIEWABLES,
    ED_3D_VIDEOS,
    ED_CE_ULTRAHD_VIDEOS,
    RECENTLY_ADDED_ED_VIDEOS,
    RECENTLY_ADDED_TV_ED_VIDEOS,
    RECENTLY_ADDED_NON_TV_ED_VIDEOS,
    RECENT_THEATRICAL_RELEASES_NON_TV_ED_VIDEOS,
    EXTENDED_VIDEOS,
    CANON_VIDEOS,

    AVAILABLE_FOR_DOWNLOAD_VIDEOS,
    ED_4K_VIDEOS,
    ED_HDR_VIDEOS,
    ED_ATMOS_VIDEOS,
    DEBUG_PAST_VIDEOS,
    DEBUG_PRESENT_VIDEOS,
    DEBUG_FUTURE_VIDEOS,
    DEBUG_UNKNOWN_VIDEOS,

    ED_NEW_RELEASES_HOLLYWOOD,
    ED_NEW_RELEASES_DIRECT_TO_DVD,
    ED_NEW_RELEASES_TV_EPISODES,
    ED_NEW_RELEASES,

    ED_NEW_RELEASES_HOLLYWOOD_EXTENDED,
    ED_NEW_RELEASES_DIRECT_TO_DVD_EXTENDED,
    ED_NEW_RELEASES_TV_EPISODES_EXTENDED,
    ED_NEW_RELEASES_EXTENDED,

    ED_NEW_RELEASES_TV_EPISODES_SHORTEN,


    ED_NEW_RELEASES_HOLLYWOOD_EXTENDED_WITH_THEATRICAL_12MO,
    ED_NEW_RELEASES_TV_EPISODES_EXTENDED_WITH_THEATRICAL_12MO,
    ED_NEW_RELEASES_EXTENDED_WITH_THEATRICAL_12MO,
    AUTO_PLAY_DISABLED

}
