package com.netflix.vms.transformer.namedlist;

public enum VideoNamedListType {

    VALID_VIDEOS,
    VALID_SUPPLEMENTALS,
    ED_SUPPLEMENTALS,
    VALID_TOP_NODES,
    VALID_ED_VIDEOS,
    VALID_ORIGINAL_TOP_NODES,
    VALID_ORIGINAL_VIDEOS,
    ED_VIDEOS,
    ED_TOP_NODES,
    ED_SHOWS,
    ED_SEASONS,
    ED_MOVIES,
    ED_EPISODES,
    ED_VIEWABLES,
    ED_CE_ULTRAHD_VIDEOS,
    RECENTLY_ADDED_ED_VIDEOS,
    RECENTLY_ADDED_TV_ED_VIDEOS,
    RECENTLY_ADDED_NON_TV_ED_VIDEOS,

    AVAILABLE_FOR_DOWNLOAD_VIDEOS,
    ED_4K_VIDEOS,
    ED_HDR_VIDEOS,

    ED_NEW_RELEASES,

    ED_NEW_RELEASES_HOLLYWOOD_EXTENDED,
    ED_NEW_RELEASES_DIRECT_TO_DVD_EXTENDED,
    ED_NEW_RELEASES_TV_EPISODES_EXTENDED,
    ED_NEW_RELEASES_EXTENDED,

    ED_NEW_RELEASES_TV_EPISODES_SHORTEN,

}
