package com.netflix.sunjeetsonboardingroot.model;

import com.datastax.driver.core.Session;
import com.netflix.aeneas.AeneasCassandraCqlUnit;
import org.cassandraunit.dataset.cql.ClassPathCQLDataSet;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;

/**
 * This test starts an embedded cassandra server that matches what Netflix runs in the cloud.
 * The AeneasCassandraCqlUnit API follow the cassandra-unit API. You can find more examples here:
 * https://github.com/jsevellec/cassandra-unit-examples
 *
 * @author This file is auto-generated by runtime@netflix.com. Feel free to modify.
 */
public class SunjeetsOnboardingRootCassandraDaoTest {
    @Rule
    public AeneasCassandraCqlUnit cassandra = new AeneasCassandraCqlUnit(
            new ClassPathCQLDataSet("setUpGreetingsDao.cql", "sunjeetsonboardingroot"));

    private SunjeetsOnboardingRootCassandraDao testDao;

    @Before
    public void before() {
        Session session = cassandra.getSession();
        testDao = new SunjeetsOnboardingRootCassandraDao(session);
    }

    @Test
    public void testLoadExistingGreeting() {
        Greeting storedGreeting = testDao.loadGreeting("yodle@yodle.net").get();
        Assert.assertEquals("yodle@yodle.net", storedGreeting.getUserEmail());
        Assert.assertEquals("Yodle", storedGreeting.getFirstName());
        Assert.assertEquals("Yo", storedGreeting.getMessage());
    }

    @Test
    public void testStoreThenLoadGreeting() {
        Greeting greeting = new Greeting();
        greeting.setUserEmail("bobby@bobby.net");
        greeting.setFirstName("Bobby");
        greeting.setMessage("Howdy");
        testDao.storeGreeting(greeting);
        Greeting storedGreeting = testDao.loadGreeting("bobby@bobby.net").get();
        Assert.assertEquals("bobby@bobby.net", storedGreeting.getUserEmail());
        Assert.assertEquals("Bobby", storedGreeting.getFirstName());
        Assert.assertEquals("Howdy", storedGreeting.getMessage());
    }
}
